---
title: "Reading list sociology"
author: "Thom Volker"
date: "2/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading list

- [x] Barrera, D., Buskens, V., 2009. Third-party effects. In: Cook, K.S., Snijders, C., Buskens, V., Cheshire, C. (Eds.), eTrust. Forming Relationships in the Online World. Russell Sage, New York, pp. 37–72.

Only laboratory experiment in which both dyadic and network embeddedness were manipulated in Trust Games in similar ways to the triadic repeated Trust Game article by Buskens, Raub and Van der Veer. This experiment however involves a more complex setting in which trustors play simultaneously rather than sequentially with one trustee, which affects the predictions.

- [x] Bolton, G.E., Katok, E., Ockenfels, A., 2004. How effective are online reputation mechanisms? An experimental study. Management Science 50, 1587–1602.

Repeated Trust Games with dyadic and network embeddedness.

- [x] Bolton, G.E., Ockenfels, A., 2009. The limits of trusts in economic transactions: investigations of perfect reputation systems. In: Cook, K.S., Snijders, C., Buskens, V., Cheshire, C. (Eds.), eTrust. Forming Relationships in the Online World. Russell Sage, New York, pp. 15–36.

Repeated Trust Games with dyadic and network embeddedness.

- [x] Casella, Alessandra, Navin Kartik, Luis Sanchez, and Sébastien Turban. 2018. “Communication in Context: Interpreting Promises in an Experiment on Competition and Trust.” Proceedings of the National Academy of Sciences 115, no. 5: 933–938.

Overview of cooperation in networks.

- [x] Sánchez, Angel. 2018. “Physics of Human Cooperation: Experimental Evidence and Theoretical Models.” Journal of Statistical Mechanics: Theory and Experiment 2018, no. 2: 024001.

Overview of cooperation in networks.

- [x] Wang, J., Suri, S., & Watts, D. J. (2012). Cooperation and assortativity with dynamic partner updating. Proceedings of the National Academy of Sciences, 109(36), 14363-14368.

Cooperation due to dynamic partner updating?

- [x] Kollock, P. (1998). Social dilemmas: The anatomy of cooperation. Annual Review of Sociology, 24, 183-214.

Annual review on cooperation.

- [x] Fehr, E., & Gintis, H. (2007). Human motivation and social cooperation: Experimental and analytical foundations. Annual Review of Sociology, 33.

Annual review on cooperation.

** Axelrod on evolution of cooperation.
- [ ] Axelrod R, D’Ambrosio L. 1994. Annotated bibliography of the evolution of cooperation. Online document: http://ippsweb.ipps.lsa.umich.edu:70/1/ipps/papers/coop 

- [x] Axelrod R, Dion D. 1988. The further evolution of cooperation. Science 242:1385–90

- [ ] Sonnemans, J., Schram, A., & Offerman, T. (1999). Strategic behavior in public good games: when partnersdrift apart. Economics Letters,62(1), 35–41

Participants play for 36 rounds in groups of four. Group composition remains constant for a minimum of three and a maximum of 12 rounds. Group composition remains constant for a minimum of three and a maximum of 12 rounds. Groups change only gradually, with at most one subject at a time leaving the group with replacement, and the timing of departure is common knowledge. This design feature is crucial because a subject leaving a group is guaranteed not to interact with his former group members again and so there is no incentive to engage in strategic behavior in the last period before leaving the group, while strategic behavior is still possible in other periods. The authors find evidence of strategic behavior in that there is a sharp decline in contributions in the last period prior to leaving a group, but they also find evidence of conditional behavior in that subjects who expect others to contribute also contributed themselves.

- [x] Andreoni, J. & Miller, J. H. Rational cooperation in the finitely repeatedprisoner’s dilemma: experimental evidence.Econ. J.103,570–585 (1993).

Quote from Andrew Mao, Lili Dworkin, Siddharth Suri& Duncan J. Watts: "If sufficiently many players in finitely repeated games are conditional cooperators, either because they harbour altruistic (i.e., other regarding) preferences or for some other reason (e.g., internalized social norms of fairness), then, it will be in the interests of the rational players to cooperate also. In that event, it has been suggested that cooperation could be sustained indefinitely (Andreoni & Miller, 1993)."

- [x] Embrey, M., Fréchette, G. R., & Yuksel, S. (2018). Cooperation in the finitely repeated prisoner’s dilemma. The Quarterly Journal of Economics, 133(1), 509-551.

Show that the duration of a finitely repeated game is highly predictive of initial cooperation levels --> indication of control - if future gains outweigh initial short-term benefits, cooperation in earlier rounds is more beneficial to do not risk possibly sanctions of alter. Note that this study probably concerns dyadic embeddedness.



# Dyadic embeddedness

## Control - endogenous

- [ ] Hauk, E. (2003). Multiple prisoner's dilemma games with(out) an outside option: An experimental study. *Theory and Decisions, 54*, 207-229. Retrieved from https://link.springer.com/content/pdf/10.1023/A:1027385819400.pdf

## Control - exogenous

# Network embeddedness

### Studies that found an effect of embeddedness on trustfulness and trustworthiness

- [x] Frey, V., & Van de Rijt, A. (2016). Arbitrary inequality in reputation systems. Scientific Reports, 6, 38304.

- Do not distinguish between learning and control.

- [ ] Bohnet, I., & Huck, S. (2013). Repetition and reputation: Implications for trust and trustworthiness when institutions change. American Economic Review, 94, 362-366.

- [ ] Bohnet, I., Harmgart, H., Huck, S., & Turan, J.-R. (2005). Learning trust. Journal of the European Economic Assocation, 3, 322-329.

- [x] Bolton, G. E., Katok, E., Ockenfels, A. (2004) How effective are electronic reputation mechanisms? An experimental investigation. Managerial Science, 50, 1587-1602.

- [ ] DiMaggio, P., & Louch, H. (1998). Socially embedded consumer transactions: For what kinds of purchases do people most often use networks? American Sociological Review, 63, 619-637.

- [ ] Gulati, R., & Gargiulo, M. (1999). Where do interorganizational networks come from? American Journal of Sociology, 104, 1439-1493.

- [ ] Huck, S., Lünser, G. K., & Tyran, J.-R. (2010). Consumer networks and firm reputation: A first experimental investigation. Economic Letters, 108, 242-244.

- [ ] Robinson, D. T., & Stuart, T. E. (2007). Network effects in the governance of strategic alliances. Journal of Law, Economics and Organizations, 23, 242-273.

### Studies that did not find an effect of embeddedness on trust or related cooperative behaviors

- [x] Corten, R., Rosenkranz, S., Buskens, V., & Cook, K. S. (2016). Reputation effects in social networks do not promote cooperation: An experimental test of the Raub & Weesie model. PlosOne, 11, e0155703. 

- [ ] Grujic, J., Fosco, C., Araujo, L., Cuesta, J. A., & Sánchez, A. (2010). Social experimentals in the mesoscale: Humans playing a spatial prisoner's dilemma. PLoS ONE, 5, e13749.

- [ ] Huck, S., Lünser, G. K., & Tyran, J. R. (2012). Competition fosters trust. Games and Economic Behavior, 76, 195-209.

- [x] Van Miltenburg, N., Buskens, V., Raub, W. (2012). Trust in triads: Experience effects. Social Networks, 34, 425-428.

### Studies find that certain institutions mitigate social dilemmas especially strongly if they were chosen endogenously

- [ ] Gürerk, Ö., Irlenbush, B., & Rockenbach, B. (2014). On cooperation in open communities. Journal of Public Economics, 120, 220-230.

- [ ] Sutter, M., Haighner, S., & Kocher, M. G. (2010). Choosing the carrot or the stick? Endogenous institutional choice in social dilemma situations. Review of Economic Studies, 77, 1540-1566.

- [x] Schneider, F., & Weber, R. A. (2013). Long-term commitment and cooperation. Working Paper 130. Department of Economics, University of Zürich. Show that a longer interaction duration (dyadic embeddedness) promotes cooperation more if it is chosen endogenously by the actors rather than imposed exogenously.

## Control - endogenous

## Control - exogenous

# Dyadic & network embeddedness

## Endogenous dyadic and network embeddedness

## Exogenous dyadic and network embeddedness

- [x] Buskens, V., Raub, W., & Van der Veer, J. (2010). Trust in triads: An experimental study. Social Networks, 32, 301-312.



# Additional readings that are not per se relevant

- [x] Simpson, B., & Willer, R. (2015). Beyond altruism: Sociological foundations of cooperation and prosocial behavior. Annual Review of Sociology, 41.

Annual review on cooperation.

- [x] Macy, M. W., & Flache, A. (1995). Beyond rationality in models of choice. Annual Review of Sociology, 21.

Moving beyond RCT in sociology?

- [x] Kroneberg, C., & Kalter, F. (2012). Rational choice theory and empirical research: Methodological and theoretical contributions in Europe. Annual Review of Sociology, 38, 73-92.

Overview of rational choice theory in sociological research.

- [ ] Edling, C. R. (2002). Mathematics in sociology. Annual Review of Sociology, 28.

See title.

- [ ] Hechter, M., & Kanazawa, S. (1997). Sociological rational choice theory. Annual Review of Sociology, 23.

See title.

- [ ] Udehn, L. (2002). The changing face of methodological individualism. Annual Review of Sociology, 28.

See title.

- [ ] Macy, M. W., & Willer, R. (2002). From factors to actors: Computational sociology and agent-based modeling. Annual Review of Sociology, 28.

See title.

- [ ] Spillman, L., & Strand, M. (2013). Interest-oriented action. Annual Review of Sociology, 39, 85-104.

See title.
