---
title: "Untitled"
subtitle: "Word count: `r wordcountaddin::word_count()`"
author: "Thom Volker"
date: "11/18/2021"
output: 
  pdf_document:
    toc: true
bibliography: "../thesis.bib"
csl: "../american-sociological-association.csl" # "/Users/thomvolker/Documents/styles/nature.csl"  #
link-citations: yes
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

## General example to introduce social dilemma situations

Social dilemmas manifest themselves throughout everyday life. When you plan to have dinner in a restaurant this Monday, you will have to trust the chef that the ingredients are fresh and of good quality. If this is indeed the case, you will enjoy an exquisite dinner that you happily pay for. The chef, who had no change to get rid of the entire bulk of food ordered before the weekend, however, prefers to sell the leftovers for money, rather than tossing these into the bin [@bourdain2013kitchen]. If you are not particularly a connoisseur, you might not even notice until you experience the discomfort later that night. Foreseeing this unpleasant situation, you may cancel your reservation and decide to cook dinner yourself. This decision would leave you, who fancied a fabulous dinner over your home-cooked meal, and the chef, who preferred to have more customers, worse off compared to the situation in which you would dine in the restaurant that solely uses the best ingredients, qualifying the situation as a social dilemma [@ostrom_behavioral_1998; @kollock_social_1998]. 

## Show how dilemma situations relate to social and economic exchange

As outlined by @buskens_raub_embedded_2002, social dilemma situations are exemplary of many economic or social exchange situations. In buyer-seller relations, for instance, the quality of the product that is provided can seldom be evaluated before the product is paid for, allowing the seller to sell a low-quality product. The buyer may anticipate on this behavior, and refuses to engage in the transaction in the first place. Consequently, the collective returns will be lower as compared to the situation in which the transaction materialized. As an example of social exchange [@blau1964exchange; @Cook2013], someone may help a neighbor, expecting that this favor will be returned in the future. However, when the time is there, it is in the neighbor's self-interest to not provide help anymore, because it is costly in terms of resources. If one anticipates on this opportunistic action, help may not be provided in the first place, leaving both actors worse off than they could have been. All these dilemma situations show that the actors involved can achieve a collectively better outcome, but that this outcome may not be reached because at least one of the actors has an incentive to act otherwise. 

## Introduce (as little as possible) terminology, which eases the explanation of embeddedness and allows to start the theory without requiring a lengthy introduction

The aforementioned examples resemble a trust problem in the sense of @coleman_foundations_1990. Coleman distinguishes between a trustor, resembling the guest, the buyer or the person who helps a neighbor, and a trustee, like the chef, the seller or the neighbor. If the trustor is trustful and places trust, the trustee may honor or abuse trust, that is, decides whether to act trustworthy. A trustor might anticipate on the trustee's incentives to abuse trust, and therefore refrain from placing trust. If the trustor does not place trust, the trustee has no opportunity to honor or abuse trust, which thus marks the end of the interaction. The trust problem can be formally analyzed under a game-theoretical framework using the Trust Game [e.g., @camerer_weigelt_sequential_1988; @dasgupta_1988]. Such theoretical analyses generally show that trust is difficult to achieve in isolated encounters [@buskens_raub_embedded_2002; @buskens_raub_handbook_2013]. Such tendencies similarly hold for a variety of other dilemma situations, that can for instance be modeled by Prisoners' Dilemmas, Helping Games or Public Goods Games. In these games, people generally speak of cooperation and defection, rather than trust and distrust.

## Introduce embeddedness (to make things more intuitive, I opted to bring in "reputation")

However, many everyday interactions can hardly be called isolated encounters, as they are often embedded in some social context [@granovetter_economic_1985]. People may go to the same restaurant or the same store repeatedly or may know other customers as well. Obviously people have recurring interactions with their neighbors and others who know these neighbors. Embeddedness operates on two different levels: the level of the dyad, which refers to the situation that the same two actors interact repeatedly, and on the level of the network, which refers to the situation in which the interacting actors share a common environment with third parties [e.g., @buskens_raub_embedded_2002; @buskens_raub_handbook_2013]. On both of these levels, embeddedness can foster trustful and trustworthy behavior through two mechanisms: control and learning [@buskens_raub_embedded_2002; @buskens_raub_handbook_2013; @buskens2018trust; @yamagishi_yamagishi_trust_1994]. 

## Shortly discuss learning, theory and evidence.

Learning refers to the fact that people may base their current behavior on their knowledge about past actions of the behavior of their current partner. When people are embedded, they can learn about the reputation of their partner, either through own experiences, or through experiences of their acquaintances. This information can be used to infer what the behavior of one's partner will be in the current interaction, and one can adapt one's future behavior accordingly. Obviously, no one wants to consume goods of inferior quality, and it is unlikely that someone who does not keep one's promises can count on much leniency on behalf of the neighborhood. Yet, if you have had many good experiences with a restaurant, or you know of others who had good experiences, you may be more inclined to eat there as well. Such learning effects have been well documented in the sociological and economic literature, both under dyadic and network embeddedness (see @buskens_raub_veer_triads_2010, @camerer_weigelt_sequential_1988, @neral_ochs_sequential_1992, @anderhub_repeated_trust_2002, @mao_resilient_cooperators_2017 and @embrey_etal_cooperation_2018 for dyadic learning effects; and see @seinen_schram_social_2006, @engelmann_firschbacher_2009, @buskens_raub_veer_triads_2010, @bolton_electronic_2004 and @wedekind_milinski_2000 for network learning effects). Hence, a bad reputation proofs to be harmful in many situations, while those with a good reputation tend to be rewarded. 

## Now focus on control, shortly theory and somewhat more on the findings

The control mechanism resembles the fact that the trustee's long-term incentives are partly under control of the trustor [@buskens_raub_embedded_2002]. When deciding how to behave, people have to take into account that their behavior now will affect their reputation, which affects how others will treat them in the future. Specifically, those who take advantage of others can be sanctioned, for example because they will not be helped or trusted anymore, while those who act kind can be rewarded by helping them in the future. Both sanctions and rewards can be implemented by the person against whom the behavior was direct to in the first place (dyadic control), but this person might also inform others who can base their behavior on this information (network control). You may, for instance, return to a restaurant you have had good experiences with, but you could also recommend this place to others. Consequently, if the long-term consequences of a poor reputation outweigh the short-term gains of opportunistic behavior, it is beneficial to adjust your behavior accordingly. People indeed tend to foresee that it pays off to act cooperatively when interacting with the same partner repeatedly, which demonstrates the presence of dyadic control effects [@dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011; @dal_bó_fréchette_determinants_2018; @embrey_etal_cooperation_2018]. Yet, the evidence is much more ambiguous when sanctions cannot be implemented by the potential victim, but only by others, representing a network control effect [@bolton_electronic_2004; @corten_etal_reputation_2016; @miltenburg_buskens_triads_2012; @buskens_raub_veer_triads_2010].

## What will we be researching in the current study

The goal of this paper is to get a clearer picture of the evidence concerning the aforementioned network control effects, using the data from multiple studies on network embeddedness. Although all of these studies assessed network embeddedness in some form, only part of these studies assessed network control effects and a subset of these studies found evidence for such effects. We will first statistically summarize the overall amount of evidence in favor of a network control effect by reanalyzing the data from a larger set of past studies. Additionally, some studies found an indication of differences with regard to network control effects according to the role of the actor. It appeared that network control opportunities had an effect on the trustfulness of those in the position to exploit their partner (i.e., the trustees in the Trust Game), but not on the trustworthiness of those who were not in this position [i.e., the trustors\; @buskens_raub_veer_triads_2010; @frey_buskens_investments_2019; @barrera_buskens_third_2009]. The second aim of our study is to quantify whether there is indeed more evidence for network control effects for trustees than for trustors. Finally, past studies consistently showed evidence in favor of dyadic control effects, but not in favor of network control effects. Our third objective thus is to statistically compare the evidence for dyadic and network control effects. These research questions have not been addressed in all experimental studies under consideration, and we will thus reanalyze the data from these studies using a consistent analysis plan. 

## How are we going to do it?

The studies considered differ considerably with respect to the experimental conditions, such as the type of game, the network size, the amount of variation in transaction partners and the number of rounds. Yet, all these studies assessed network embeddedness and allow to test for control effects. Hence, although not explicitly designed as such, these studies can be considered conceptual replications. While previous research has particularly stressed the importance of exact, direct or close replications, conceptual replications have the advantage that they do not rely on a particular design. A robust line of evidence that allows for greater generalizability is necessarily built by combining various ways of testing the same hypotheses, using different sources of data and different methodologies and hence benefits from the synthesis of multiple conceptual replications [e.g., @buskens_raub_handbook_2013; @munafo_robust_2018; @lawlor_triangulation_2017; @jackson_cox_experimental_2013]. However, conventional approaches such as meta-analysis do not allow for the resulting heterogeneity between studies [@lipsey_wilson_2001; @sutton_bayesian_meta2001; @cooper_handbook_2009]. To overcome these problems, we will use a novel method called Bayesian Evidence Synthesis [@kuiper_combining_2013]. 

Bayesian Evidence Synthesis (*BES*) is built upon the foundation of the Bayes Factor [@kass_raftery_bayes_factors_1995]. This method allows researchers to pool evidence for a specific hypothesis over multiple studies, even if the studies have varying study designs designs. Using *BES*, the evidence in favor of a network control effect over these studies can be summarized statistically. In every study, a hypothesis on the effect of control through network embeddedness can be constructed, and it's support can be quantified using a Bayes Factor ($BF$). The study-specific $BF$'s can subsequently be combined to quantify the overall amount of evidence for the overarching hypothesis that network control fosters trust, regardless of the study-specific differences with regard to design and operationalizations of key variables. Rather than pooling effect sizes, *BES* allows to quantify the evidence over studies in favor of a more general scientific theory. Hence, besides contributing substantively, we aim to contribute methodologically, by outlining how *BES* can be used to statistically summarize the evidence in favor of a hypothesis over conceptual replications, and how this statistical synthesis of results should be interpreted.




<!-- Ultimately, this study aims to address both empirical and methodological issues. So far, no attempt has been made to statistically summarize the findings on the network control hypothesis. In fact, only few studies explicitly addressed the network control hypothesis. In the current study, data from varying past experiments (see Table \@ref(tab:studies-table)) will be reanalyzed using a consistent analysis plan, to summarize the evidence in favor of the network control hypothesis quantitatively. We will expand on the original analyses to get a more complete picture of the network control hypothesis. Second, although the eight studies included in this paper are not explicitly designed as such, they can be considered conceptual replications. While previous research has particularly stressed the importance of exact, direct or close replications, conceptual replications have the advantage that they do not rely on a particular design. A robust line of evidence that allows for greater generalizability is necessarily built by combining various ways of testing the same hypotheses, using different sources of data and different methodologies and hence benefits from synthesis of multiple conceptual replications [e.g., @buskens_raub_handbook_2013; @munafo_robust_2018; @lawlor_triangulation_2017; @jackson_cox_experimental_2013]. It will be outlined how *BES* should be applied to statistically summarize the evidence in favor of a hypothesis over such conceptual replications, and how the results of such an analysis should be interpreted.  -->



<!-- To answer these research questions, we will use a novel method called Bayesian Evidence Synthesis [@kuiper_combining_2013]. Bayesian Evidence Synthesis (*BES*) is built upon the foundation of the Bayes Factor [@kass_raftery_bayes_factors_1995]. This method allows researchers to pool evidence for a specific hypothesis over multiple studies, even if the studies have varying study designs designs. This flexibility is required, because the studies considered differ considerably with respect to the experimental conditions, such as the type of game, the network size, the amount of variation in transaction partners and the number of rounds. Due to this variation, classical meta-analytic approaches are infeasible [@lipsey_wilson_2001; @sutton_bayesian_meta2001; @cooper_handbook_2009]. However, all studies under consideration studied network embeddedness and allow to test for control effects. Using *BES*, the evidence in favor of a network control effect over these studies can be summarized statistically. In every study, a hypothesis on the effect of control through network embeddedness can be constructed, and it's support can be quantified using a Bayes Factor ($BF$). The study-specific $BF$'s can subsequently be combined to quantify the overall amount of evidence for the overarching hypothesis that network control fosters trust, regardless of the study-specific differences with regard to design and operationalizations of key variables. Hence, rather than pooling effect sizes, *BES* allows to quantify the evidence over studies in favor of a more general scientific theory.  -->
<!-- Although the studies under consideration are not explicitly designed as such, they can be considered conceptual replications. While previous research has particularly stressed the importance of exact, direct or close replications, conceptual replications have the advantage that they do not rely on a particular design. A robust line of evidence that allows for greater generalizability is necessarily built by combining various ways of testing the same hypotheses, using different sources of data and different methodologies and hence benefits from synthesis of multiple conceptual replications [e.g., @buskens_raub_handbook_2013; @munafo_robust_2018; @lawlor_triangulation_2017; @jackson_cox_experimental_2013]. We thus aim  -->


# Control effects on trust: The effect of network control

[[In de volgende alinea twijfel ik een beetje of ik de payoffs in de trust game moet introduceren. Vanuit het perspectief om 'technicalities' zoveel mogelijk te vermijden deed ik het vooralsnog niet, maar het zou de beschrijving van de karakteristieken van de verschillende studies wellicht makkelijker maken.]]

Many theoretical contributions showed that trust is difficult to achieve in isolated encounters [e.g., @buskens_raub_handbook_2013; @binmore_playing_2007]. The key here is that if today's actions do not affect future outcomes, people have no incentive to base their decisions on anything other than what they find important now. In other words, if the focal interaction is not related to any future interactions that the actors are involved in, there are no control opportunities. Hence, if trustees have short-term incentives for abusing trust, there is nothing that withholds them from abusing trust if they are in the situation to do so. Accordingly, if trustors know that trustees have short-term incentives to abuse trust, and that abusing trust has no consequences other than the outcome of the current interaction, they may protect themselves against an unwanted outcome by not placing trust in the first place. Hence, the trustfulness of the trustor is predominantly based on the expectation regarding the trustworthiness of the trustee [@buskens_raub_embedded_2002]. 

Taking into account the social context, the incentives of the actors may change. When interactions are embedded, the trustee now has to balance the short-term incentives for abusing trust with the long-term costs. If the same two partners interact repeatedly, the gains from a flourishing partnership may be higher than the gains from exploiting your partner once and being punished for this act thereafter. The fact that some of the trustee's long-term incentives are under control of the trustor, may induce a shift in behavior. A trustor can sanction untrustworthy behavior by not placing trust in any future interaction, and reward the trustee by placing trust otherwise, which is often referred to as conditional cooperation [@taylor_cooperation_1987] or direct reciprocity [@nowak_five_2006; @rand_nowak_cooperation_2013]. Game-theoretical analyses show that if the costs of future retaliation outweighs the short-term gains of abusing trust, it is in the trustee's self-interest to behave trustworthy [@kreps_1990]. Accordingly, the trustor might foresee that an abuse of trust would be against the interests of the trustee, and thus can safely place trust.^[A more formal discussion can be found in the work of @buskens_raub_handbook_2013 and @buskens2018trust.] Indeed, actors are less likely to exploit partners who they expect to interact with repeatedly, providing clear evidence for control effects in the dyadic case [@dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011; @dal_bó_fréchette_determinants_2018; @embrey_etal_cooperation_2018].

When trustees interact with a network of trustors who can share information among each other, rather than a single trustor, the same mechanism holds. When the current partner of the trustee can inform other trustors, the long-term payoffs of the trustee are still partly under control of the current partner. If future trustors are informed about the trustee's abuse of trust, they might refrain from placing trust as well [which is often called indirect reciprocity\; @nowak_five_2006; @nowak_sigmund_evolution_2005]. Accordingly, the trustee's long-term losses may still outweigh the short-term gains from the abuse of trust, which may mitigate the incentive for abusing trust. However, the severity of future sanctions, and thus the incentive to honor trust in the focal interaction, depends on characteristics of the network. If the trustors that obtain the information have a small chance of interacting with the trustee, the fact that they are informed might not matter much. Thus, the threat of future sanctions must be credible to have bite. 

[[Denken jullie dat ik netwerk inbedding nog moet uitsplitsen in vervanging en aanvulling op dyadische inbedding? Mij leek het handig ivm de experimenten die later gaan komen, dan is het alvast geïntroduceerd, en kan ik het verhaal over de individuele studies kort(er) houden. Als het niet relevant is, voeg ik de komende twee alinea's samen om sneller bij the hypothese uit te komen.]]

Dyadic embeddedness can be entirely replaced by network embeddedness, such that in every interaction the trustee meets a new trustor [@kreps_1990; @kandori_social_1992]. One might, for example, not return to the same restaurant repeatedly, but inform others about experiences with this restaurant. If the trustors are reliably informed about the trustee's behavior in earlier interactions, they can condition their actions on previous outcomes. Accordingly, similar sanctions can be applied as under dyadic embeddedness, albeit by different trustors. If these sanctions are sufficiently severe, it is in the trustee's self-interest to honor trust. Moreover, the trustors can infer that due to control opportunities, the trustee may be unlikely to abuse trust, and therefore may be more inclined to place trust. Hence, placing and honoring trust becomes more tempting when the trustee interacts more often with other, informed, trustors.^[Note that one of the key assumptions on network control effects is that information is reliable, and is provided regardless of incentive problems [e.g., @buskens_raub_embedded_2002].] Although network embeddedness effects have been regularly found in the absence of dyadic embeddedness [in Trust Games, e.g., @bohnet_huck_2004; @bohnet_learning_2005; @huck_competition_2012; duffy2013social\; and in other dilemma games, e.g. @seinen_schram_social_2006; @pfeiffer_etal_value_2012], network control effects specifically have been assessed by @bolton_electronic_2004 and @corten_etal_reputation_2016, where only the former found evidence for such effects. However, as most of these studies have not disentangled learning and control effects explicitly, it remains ambiguous whether network control indeed fosters trust.

Likewise, network embeddedness can complement dyadic embeddedness [e.g., @buskens_trust_2003]. One might imagine the situation in which you repeatedly visit the same restaurant, but additionally inform others about your experiences. This situation implies that both the trustor involved in the focal interaction, as well as the trustors who are informed, can sanction the trustee if trust is abused. The trustee thus has to consider that both sanctions and rewards can be implemented multiple times by multiple actors. Sanctions will be more severe if the likelihood that information about the trustee's past behavior is disseminated increases, but also when the number of informed future partners of the trustee increases. If the trustor and the trustee are aware of such control opportunities, the trustee is expected to be more likely to honor trust, allowing the trustor to place trust more easily. Some support for such network control effects alongside dyadic embeddedness have indeed been found by @buskens_raub_veer_triads_2010, @barrera_buskens_third_2009 and @frey_buskens_investments_2019, but not by others [@miltenburg_buskens_triads_2012]. Hence, it is hypothesized that the trustee's trustworthiness increases in the amount of network control opportunities ($H_1$), and that the trustor's trustfulness increases in the amount of network control opportunities ($H_2$).

## Differences between network control effects for trustors and trustees

Given that both the trustor and the trustee receive the same information before they enter an interaction, the amount of network control opportunities are known to both. However, this is not to say that these control opportunities are also evaluated in the same way by both actors. In fact, it may be easier to anticipate on such network control opportunities for the trustee than for the trustor [@buskens_raub_veer_triads_2010]. For the trustee, it may be relatively straightforward to anticipate on the fact that abusing trust in a given round will result in repercussions during later rounds. The reasoning here only requires to think one step ahead: if future trustors sanction an abuse of trust, abusing trust will be costly, and if these costs outweigh the gains of abusing trust, it is not worthwhile to act opportunistically. 

The trustor, however, has to to reason multiple steps ahead before the effects of network control become obvious. Specifically, the trustor has to speculate on how the trustee's behavior will change according to future sanctions by other trustors. That is, the attractiveness of placing trust increases only if the trustor foresees that the trustee anticipates on how abusing trust now will affect the trustfulness of future trustors, and thus on how future trustors will condition their behavior on the trustee's current actions. If you don't know whether the chef foresees that an unpleasant experience for you may result in others who in turn avoid the restaurant as well, the risk of eating might be too large, leading you to cook your own meal. In short, people tend to have difficulties overseeing the complex dynamics of situations with multiple interdependent actors, especially if they have no experience with such situations [@binmore_playing_2007; @dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011; @buskens_raub_veer_triads_2010; @milinski_cooperation_2001]. Accordingly, it is hypothesized that the network control effect is stronger for the trustee than for the trustor ($H_3$). 



## Differences between dyadic control and network control

[[Ik heb het gevoel dat qua opbouw van complexiteit en specificiteit het beter zou zijn om dit te bespreken voordat de verschillen tussen trustor en trustee besproken worden. Echter, ik heb enkele bedenkingen bij het eerlijk kunnen vergelijken van van dyadische en netwerk controle effecten (hier kunnen we het woensdag over hebben), waardoor het misschien niet gepast is om gegeven de huidige set van studies deze effecten te vergelijken.]]

Similarly, network control opportunities may be more difficult to evaluate compared to dyadic control opportunities, and there are multiple reasons why this may be the case. First of all, trustors have to rely on third parties to implement sanctions against a trustee who abused trust. However, third parties may abstain from sanctioning, for example because they observe that the trustee has already been sanctioned or because they think that the trustee receives a second chance. Likewise, a trustor who observed an abuse of trust may still believe that a trustee honors trust most of the time, and thus infer that the probability that trust will be abused is relatively small. Another reason is that information from third parties can be inconsistent with one's own experiences. If someone has never abused your trust, you may hardly worry about being exploited regardless of the fact that a trustee has exploited someone else. Although all these factors primarily concern the trustfulness of the trustor, the trustee may envision that such factors play a role. If a trustee expects that sanctions sanctions implemented by third parties will be less severe than sanctions implemented by the focal trustor in future interactions, the willingness to honor trust may subsequently decrease. Lastly, it may be that under dyadic embeddedness the trustor places trust, because without placing trust initially, it is not possible to build a mutually profitable relationship. However, under network embeddedness, trustors may try to learn from the experiences of others. Hence, despite control opportunities, the trustors may first rely on the experiences by others, before they are willing to take the risk to get exploited. Differences between dyadic embeddedness and network embeddedness have been found by others as well [e.g., @bolton_electronic_2004; @bohnet_huck_2004], but the focus has not been on control effects yet. Combining all these factors, it can be hypothesized that the dyadic control effect is stronger than the network control effect, for the trustfulness of the trustors ($H_4$), as well as the trustworthiness of the trustee ($H_5$).

