---
title: |
  | 
  |
  |
  | **Literature Review**
  |
  |
  | Embeddedness and cooperation: The effect of control
  |
  |
  |
author: |
  | Thom Volker (5868777)
  |
  |
  | Supervisors: Prof. dr. ir. Vincent Buskens & Prof. dr. Werner Raub
  |
  |
  | *Sociology and Social Research Master's programme*
  |
  | *Utrecht University*
  |
  |
  |
  |
  | `r format(Sys.time(), '%B %d, %Y')`
  |
  |
  | `r paste0("Word count (excluding in-text references and appendix): ", wordcountaddin::word_count(), " (5956)")`
  | 
  |
  |
abstract: 'How cooperation between human beings emerges and prevails is one of the longest standing research questions in the social sciences. Game-theoretical predictions render cooperation between rational and selfish individuals in isolated social dilemmas impossible. However, taking relationships between the actors involved (dyadic embeddedness) and relationships between the actors involved and third-parties (network embeddedness) into account, cooperation between rational and selfish individuals is possible. Here, theoretical and experimental research on dyadic and network embeddedness is reviewed, with a specific focus on the mechanism called "control", which reflects future sanction opportunities of the actors involved. It is shown that embeddedness in general, and control opportunities specifically, indeed foster cooperation, although this effect is more pronounced and more consistently present in dyadically embedded interactions.'
output:
  bookdown::pdf_document2:
    number_sections: true
    df_print: kable
    highlight: pygments
    toc: true
# output:
#   bookdown::word_document2:
#     number_sections: true
#     df_print: kable
#     toc: true
mainfont: Calibri
sansfont: Calibri
linestretch: 1.5
fontsize: 11pt
params: 
  !r Sys.setlocale("LC_TIME", "C")
indent: true
tables: true
header-includes:
  - \usepackage{caption,multirow,array,float}
  - \usepackage{wrapfig}
  - \usepackage{booktabs}
  - \DeclareCaptionLabelSeparator*{spaced}{\\[2ex]}
  - \captionsetup[table]{textfont=it,format=plain,justification=justified,
                         singlelinecheck=false,labelsep=spaced,skip=0pt}
bibliography: "../../thesis_literature.bib"
csl: "../../apa-6th-edition.csl" # "/Users/thomvolker/Documents/styles/nature.csl"  #
link-citations: yes
linkcolor: blue
---

\newpage


<!-- Quote ideas -->
<!-- - Trust dies but mistrust blossoms ~ Sophocles -->
<!-- - The best way to find out if you can trust somebody is to trust them ~ Ernest Hemingway -->
<!-- - Trust comes on foot, but leaves on horseback ~ Dutch proverb -->
<!--
# Key words

Key words:

- Dyadic + network embeddedness (focus on network embeddedness for thesis itself).
- Use of own (readily available) data
- Try to align the M&S project and SaSR project as much as possible.
- Endogenous + exogenous (might not be fruitful in the thesis itself).
- Note that the two theses are to be written in parallel, and have to be finished in May 2022.
-->

# Introduction

Social dilemmas are at the core of everyday life. Students may anticipate a good grade for group work with minimal effort by free-riding on the work of their peers, researchers could obtain another publication by letting their collaborators do the lion's share of the required work [@corten_buskens_cooperation_2020] and a car dealer may maximize the returns of a transaction by hiding several vehicle defects when selling a second-hand car to a relatively uninformed customer [@buskens_weesie_experiment_2000]. Under the assumption of "social isolation", reflecting that the interacting actors can be considered perfect strangers that do not anticipate any future interactions, actors can maximize their individual returns by behaving uncooperatively. However, if all actors involved would apply this strategy, the students will not obtain a good grade, the researchers will not publish a joint paper, and the intended transaction will not materialize. The collective returns that emerge from self-regarding, goal-directed behaviour would be lower than what could have been achieved under mutual cooperation: hence the term "social dilemma" [@ostrom_behavioral_1998; @kollock_social_1998]. 

Theoretical predictions render a cooperative interaction between two actors in an isolated social dilemma impossible [e.g., see @luce_raiffa_games_1989 for the Prisoner's Dilemma; and @buskens_raub_embedded_2002 for the Trust Game]. Consider for example the standard one-shot Prisoner's Dilemma, in which two actors simultaneously decide to cooperate or defect. Regardless of the choice of one's partner, an individual actor obtains the highest payoff by acting uncooperatively. Defecting, rather than cooperating, leads to a higher payoff when the other player cooperates, as well as when the other player defects. Hence, the Nash equilibrium is mutual defection, even though mutual cooperation would yield a Pareto improvement, in the sense that all players would be better off. Contrary to these ominous theoretical predictions, in practice researchers generally find non-negligible rates of cooperation in one-shot games [e.g., see @cooper_et_al_cooperation_1996; @hayashi_etal_reciprocity_1999; @snijders_keren_trust_2001], although these cooperation rates tend to decline when participants gain experience with these games [@dal_bó_cooperation_2005].

Multiple scholars, however, noted that most real-life interactions do not take place in social isolation, but are actually embedded [e.g., @axelrod_cooperation_1984; @granovetter_economic_1985]. Embeddedness refers to the fact that the actors involved share a common environment that could foster cooperation [e.g., @yamagishi_yamagishi_trust_1994; @buskens_raub_embedded_2002]. The actors may have interacted in the past, and/or speculate on interacting in the future, which is referred to as *dyadic embeddedness* [@buskens_raub_embedded_2002]. Additionally, the actors may be connected indirectly, through third parties that have interacted with any of the two in the past, or speculate on doing so in the future, which is referred to as *network embeddedness* [@buskens_raub_embedded_2002]. Both dyadic and network embeddedness, which may apply simultaneously, potentially foster cooperation.

In this review, it will be assessed how, from a game-theoretic perspective, embeddedness affects cooperation, with an explicit focus on experimental studies. First, it will be illustrated which hypotheses on the effects of embeddedness can be derived from game-theoretical models. These models assume rationality of the players, in the sense that the actors involved maximize their utility given the expectations on the behaviour of their partner, using the common knowledge that all actors know all elements of the game, and know that all other actors know all elements of the game. Notably, inferring the utilities of the actors involved is often complicated, because it is not explicit how actors value potential payoffs. Throughout this review it is generally assumed that actors are self-regarding, and thus only care about their own payoffs. In the experiments considered, these payoffs yield points that are translated into money. If required, these rather strict assumptions can be relaxed to derive new hypotheses. Furthermore, the empirical findings discussed in this review generally originate from $2$-person Prisoner's Dilemma Games or Trust Games. Specifically, in most experiments considered, the behaviour of an actor only affects oneself, as well as the single actor toward whom this behaviour is directed. When occasionally another type of game or an $N$-person game (i.e., a game in which the behaviour of an actor is directed toward more than one others) is discussed, this will be explicitly addressed. This review will be concluded with a discussion of the empirical findings, the implications of these findings and possible directions for future research.

# Embeddedness effects

In the game-theoretic literature, there are two mechanisms through which embeddedness is considered to affect cooperation between actors: *control* and *learning* [e.g., @yamagishi_yamagishi_trust_1994; @buskens_raub_handbook_2013]. Control, also termed control through "voice" in the sense of @hirschman_voice_1970, reflects the opportunity to sanction opportunistic behaviour by exerting control over one's partner's long-term returns and will be the focus of this review. Under dyadic embeddedness, one can punish the defection of one's interaction partner in a previous interaction by refraining from cooperation in current and future interactions [i.e., an actor can rely on direct reciprocity; @nowak_evolving_2012]. Additionally, under network embeddedness, one might inform future transaction partners of a defecting actor, who can in turn refuse to cooperate with this actor [which is also called indirect reciprocity; @nowak_evolving_2012; @sigmund_moral_2012]. Hence, the short-term benefits of acting uncooperatively come with the prospect of future retaliation, hanging over the head of opportunistic actors as the sword of Damocles. Notably, what @buskens_raub_handbook_2013 termed "control" differs from what is called "the illusion of control" in the social psychological literature [e.g., @morris_distinguishing_1998; @hayashi_etal_reciprocity_1999]. Where "control" in the sense of @buskens_raub_handbook_2013 refers to actual sanctioning opportunities, "the illusion of control" concerns the idea that one might act as if it is possible to control the behaviour of one's partner in one-shot games, if one's decision is made prior to the decision of one's partner, even though no information is transferred between the players [@morris_distinguishing_1998]. 

Learning refers to the situation where the actors involved have interacted in the past, when they are embedded dyadically, and hereby gained information about each other's past behaviour [see @buskens_raub_handbook_2013 for a more thorough discussion and reflections on how learning fits into a game-theoretic paradigm]. If one's partner behaved cooperatively in the past, one may infer that this partner will behave cooperatively again in the current and future transactions. When the actors involved are embedded in a common network, the actors may learn from others how their transaction partners behaved in interactions with third parties. If one's current partner behaved cooperatively during past interactions with third parties, one might infer that the transaction partner will cooperate in the current transaction as well. Obviously, when an actor's partner has abused cooperative behaviour of this actor, or of a third party, the actor may not be willing to take the risk of getting exploited, and will defect in the current interaction.

A second distinction relates to the nature of the embeddedness of a transaction. Namely, in research settings, transaction partners are often matched by researchers for a prespecified duration, a situation that is commonly referred to as *exogenous embeddedness*. However, in real life, people often deliberately choose their partners, at least to a certain extent [@yamagishi_prisoners_1994; @chaudhuri_experiments_2009]. Some researchers tried to incorporate this characteristic of real-life encounters in experiments by letting participants choose their transaction partners or specify the interaction duration, which is referred to as *endogenous embeddedness*. However, under the assumption of rationality, no differences between exogenously and endogenously established relationships are to be expected. The formal requirements of a relationship that allow for cooperation to be supported in equilibrium do not depend on whether the relationship is established exogenously or endogenously, and the actors should theoretically only care about whether these prerequisites are met. However, for other reasons that will be discussed in later sections, endogenously formed relations may have a larger effect on cooperation than exogenously formed relationships [e.g., @chaudhuri_sustaining_2011; @wang_cooperation_2012; @schneider_weber_cooperation_2013; @frey_buskens_investments_2019]. 

\begin{table}[h!]
\begin{center}
\caption{Two forms of embeddedness separated by how these can be established.}
\label{Table:1}
  \begin{tabular}{ p{3cm} p{6cm}  p{6cm} } \\
    \hline
    & \multicolumn{2}{c}{Two forms of embeddedness} \\
    \hline
    Two ways of establishment &
    \multicolumn{1}{ c } {Dyad} & 
    \multicolumn{1}{ c } {Network} \\
    \hline
    Exogenous&
    Actors are matched by the researcher for a prespecified number of rounds.&
    Actors are matched by the researcher with a new partner every round, but obtain information on their partner's past behaviour from third parties. \\
    Endogenous&
    Actors are matched by the researchers but deliberately choose their interaction duration.&
    Actors choose an interaction partner every round, potentially based on information from third parties. \\
    \hline
  \end{tabular}
\end{center}
\end{table}

The subsequent sections will be concentrated around the question to what extent control affects cooperation. Hence, the effect of learning, as well as alternative explanations for the emergence of cooperation such as inequity aversion or altruism [e.g., @fehr_schmidt_fairness_1999; @dreber_etal_altruism_2014; @carpenter_altruism_2008] fall beyond the scope of this review. A distinction will be made between control under dyadic embeddedness and under network embeddedness, as well as between exogenously and endogenously formed relationships (Table \ref{Table:1}). 

Note that a great deal of the work published in this area has not distinguished between learning and control explicitly, but merely addresses the question how different forms of embeddedness in general affect cooperation. Nevertheless, it is often possible to assess the effect of control, either explicitly or implicitly. In general, there are two ways to disentangle learning and control. The first possibility is to study solely behaviour of participants in the first round of a given game, because then no learning could have taken place [e.g., @dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011; @embrey_etal_cooperation_2018]. The second way, which is often used to analyse behaviour in finitely repeated games, is to assess the effect of the number of rounds left, after controlling for any learning that could have taken place [e.g., @bolton_electronic_2004; @buskens_raub_veer_triads_2010]. Specifically, previous actions by an actor's transaction partner are taken into account when analysing the behaviour of an actor in any given round and assessing the effect of the number of rounds to play.

# Control effects under dyadic embeddedness

Applying the game-theoretic assumptions as outlined above on an isolated social dilemma renders cooperation theoretically impossible. Consider the Prisoner's Dilemma and the Trust Game as two canonical examples. In a Prisoner's Dilemma, equilibrium behaviour yields mutual defection, as defection is a strictly best response, even though mutual cooperation would yield a Pareto-improvement. Similar reasoning applies in a one-shot Trust Game. In a Trust Game, rather than mutually risking exploitation, only the trustor, who decides whether or not to trust the trustee, risks being exploited. The trustee on the other hand, has to decide whether to honour or abuse trust, if trust is placed, but cannot choose between these options if no trust is placed. Equilibrium behaviour implies that a trustee, if given the opportunity, would abuse trust. The trustor, realizing that trust will be abused if it is placed, withholds trust. Once again, the outcome where no trust is placed is Pareto-suboptimal, as both players would be better off if trust is placed and honoured. However, cooperation can emerge among selfish and rational actors by taking dyadic embeddedness into account. 

## Control effects in exogenously established dyadic relations

### Infinitely repeated games

As an extension of a one-shot game, consider the infinitely repeated Prisoner's Dilemma. The Prisoner's Dilemma is now played indefinitely often. After each round, a new round will be played with continuation probability $\delta$, which @axelrod_cooperation_1984 aptly termed "the shadow of the future", and the game will end with probability $(1-\delta)$. The introduction of a continuation probability allows the actors to condition their behaviour in future rounds on the outcome of the current round. If the continuation probability is sufficiently large with respect to the short-term incentives to behave uncooperatively, mutual cooperation can be supported in an equilibrium that cannot be payoff dominated by other equilibria [e.g., see @roth_murnighan_1978 for the technical details]. The prospect of mutual cooperation allows for control, in the sense that cooperative behaviour of one's partner in the current round can be rewarded with cooperative behaviour in future rounds, as well as opportunistic behaviour can be punished with defection. Hence, behaving cooperatively can be in the self-interest of rational players. Following @buskens_raub_handbook_2013, qualitative predictions about the behaviour of the actors involved can be derived. Without going into the details, it can be expected that cooperation is more likely to emerge if the continuation probability increases, and when the gains of a single, unilateral defection decrease. Namely, when the continuation probability increases, and when the gains of a single, unilateral defection decrease, future sanctions become more threatening, expectedly resulting in more control opportunities and hence more cooperation. Note that similar predictions apply to a Trust Game and a broader set of social dilemma games [e.g., @buskens_raub_handbook_2013]. 

@roth_murnighan_1978 and @murnighan_roth_1983, who initiated experimental research on cooperation in infinitely repeated Prisoner's Dilemmas, showed that cooperation became more likely under a higher continuation probability than under a lower continuation probability. Nevertheless, the increase was small, and the authors concluded that the value of the continuation probability hardly affects cooperation. However, in these studies, the participants played against the experimenters, rather than against each other, and the points participants earned during the experiments were not linearly translated into the monetary rewards the subjects could earn, which potentially affected the incentives of the subjects. @dal_bó_cooperation_2005 improved upon this initial work, and found that first round cooperation rates increased with the continuation probability. Particularly, the differences in cooperation between the continuation probabilities increased with the amount of experience the participants gained. Hence, people become more willing to cooperate when future transactions weigh more heavily on one's total payoff.

Similar observations were made by Dal Bó and Fréchette [-@dal_bó_fréchette_evolution_2011; -@dal_bó_fréchette_determinants_2018]. These authors argued that the limited effect of increasing the continuation probability in earlier studies was due to the fact that participants have to gain experience to properly evaluate the meaning of this increase. With sufficient experience, participants cooperated more often when cooperation was supported in equilibrium, and defected when it was not. Specifically, the continuation probability had a positive effect on first round cooperation. Moreover, the authors showed that as the gains from unilateral defections increased, cooperation was less likely to occur. Hence, in infinitely repeated games, studies consistently show that cooperation increases with the expected length of the game and decreases with the temptation to unilaterally defect, consistent with the hypothesized effects of control.

### Finitely repeated games

Control effects in dyadic relations can also be studied in finitely repeated interactions, where actors play a game for a fixed number of rounds. However, assuming rationality as defined above, it follows from backward induction that no cooperation is possible in finitely repeated games [e.g., @luce_raiffa_games_1989; @selten_chain_1978]. Namely, in the last round of the game, non-cooperative behaviour cannot be punished in any subsequent round, and hence, defecting is a strictly dominant strategy. As actors defect in the final round, actions in the penultimate round do not affect behaviour in the last round, and again, no actor has an incentive to cooperate. This pattern repeats itself to the first round of the game, and hence, assuming rationality, no cooperation is predicted in any round. 

However, when relaxing the assumption that actors have complete information, cooperation can be supported in equilibrium until the final rounds of the game [@kreps_et_al_rational_1982; @kreps_wilson_reputation_1982]. If an actor beliefs with sufficiently high probability that a partner has no incentive to defect until this partner is defected on, the benefits of mutual cooperation outweigh the gains of exploiting such a conditionally cooperative partner in an early round and being punished with defection thereafter. The prospect of mutual cooperation directly allows for the introduction of control [@buskens_raub_handbook_2013]. Namely, after an actor defects, the actor proved to be no conditional cooperator, and the finitely repeated game would continue with mutual defection hereafter. As long as both players cooperate, it cannot be known whether any of the two players is a conditional cooperator. The actors can thus control one another, because future payoffs depend on one's behaviour in the current round. It follows from this model that cooperation increases with the number of rounds to be played and decreases with the temptation to defect. Additionally, it is expected that in the final rounds of the finitely repeated game, when the long term benefits of mutual cooperation no longer outweigh the short-term costs of maintaining one's reputation (i.e., the opportunities to control future behaviour of one another diminish), actors will try to exploit their partners.

It appeared that subjects generally act cooperatively in initial rounds of a finitely repeated game, rendering the backward induction model less plausible than the sequential equilibrium model by @kreps_wilson_reputation_1982 [e.g., @camerer_weigelt_sequential_1988; @neral_ochs_sequential_1992; @mao_resilient_cooperators_2017]. Rapoport [-@rapoport_order_1997, 122], consequently, concluded that in practice, subjects do not rely on, or are not capable of, backward induction. In line with the hypothesized effects of control, cooperation generally sharply decreases toward the end of the game [e.g., @buskens_raub_veer_triads_2010; @miltenburg_buskens_triads_2012; @embrey_etal_cooperation_2018; @mao_resilient_cooperators_2017]. However, this decline in cooperation cannot entirely be ascribed to the lack of control opportunities in the final rounds of the game. Participants may namely refrain from cooperation for three different reasons, of which the latter two reflect control. First, defection could be a response to defection of one's partner in earlier rounds. Second, an actor may figure (perhaps from previously played games) that in final rounds of the game, hardly any cooperation is possible, and hence defecting serves as a protection against being exploited. Third, an actor may realize that the short-term benefits of defecting outweigh the possible returns of another round of mutual cooperation. 

@buskens_raub_veer_triads_2010 explicitly studied the presence of control effects in a Trust Game, and found, under dyadic embeddedness, a positive effect of the number of rounds still to be played on cooperation, for both the trustor and the trustee, after controlling for learning effects. Other studies corroborated the finding that the number of rounds that are to be played affects cooperation rates. @embrey_etal_cooperation_2018 performed a meta-study with data from multiple previously held experiments on finitely repeated Prisoner's Dilemma games by @andreoni_miller_cooperation_1993, @dal_bó_cooperation_2005, @cooper_et_al_cooperation_1996, @bereby_roth_cooperation_2006 and @friedman_oprea_continuous_2012. The combined evidence from these studies and a newly designed experiment, showed that first round cooperation rates, where no learning could have occurred, increased with the length of the game and that this effect increases with the experience of the subjects. Additionally, it was shown that cooperation increases when the temptation to unilaterally defect becomes smaller. @miltenburg_buskens_triads_2012 and @mao_resilient_cooperators_2017 also showed the importance of experience, in the sense that with experience, near perfect cooperation can be achieved in early rounds that remains above 80% until the final three rounds, but decreases to negligible levels shortly hereafter. However, learning and control effects were not explicitly distinguished in these analyses. Notably, the latter experiment is repeated on twenty consecutive days, with twenty 10-round games per day, and showed that the pattern of high initial cooperation and a strong end-game effect keeps repeating itself, regardless of the fact that actors experience that in final rounds cooperation seldom prevails. Conclusively, in line with the expectations, cooperation rates increase with the importance of future interactions and decrease in the final rounds of the game, showing the importance of future sanction opportunities for cooperation.

Overall, both studies on infinitely and finitely repeated games showed the importance of the prospect of future interactions for cooperation. However, it also appeared that cooperation rates in first rounds of infinitely repeated games are systematically higher than cooperation rates in the first rounds of finitely repeated games of the same expected length (i.e., an expected length of 2 and 4 rounds), especially after the subjects have gained experience with the game they play [@dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011]. It seems plausible that in finitely repeated games, subjects understand that cooperation in final rounds no longer outweighs the short-term gains of defecting, or the risk of being defected upon, and thus defect themselves. Hence, control opportunities are hardly present in the final stage(s) of a finitely repeated game, and the overall sanctioning opportunities are thus smaller in a finitely repeated game than in an infinitely repeated game of the same expected length. Consequently, first round cooperation in finitely repeated games may decrease, due to this reason.

## Control in endogenously established dyadic relations

The previous section displayed a relatively consistent effect of control in exogenously embedded dyadic interactions. However, in many real-life interactions, dyadic embeddedness is not imposed exogenously, but established intentionally by the actors involved [@kollock_emergence_1994]. Under the assumption of rationality, no differences between exogenously and endogenously established relationships are to be expected, and hence, similar hypotheses on control effects apply as outlined in the previous section. Yet, it is often remarked that selection may play a role when actors can set up relationships endogenously. For example, it may be that actors who realize that, under embeddedness, cooperation is more likely to flourish, will establish embeddedness and behave cooperatively, while actors who do not see such benefits do not engage in embeddedness and are more likely to defect [for a theoretical model, see, e.g., @schneider_weber_cooperation_2013]. Following these lines of reasoning, cooperation may be higher under endogenously established dyadic relationships than under exogenously established ones. A more thorough discussion of (empirical findings concerning) such hypotheses is left for future work; the following section is limited to the discussion of control effects under endogenously established dyadic embeddedness.

Empirical studies show that dyadic embeddedness also fosters first-round cooperation when it is chosen by the actors involved in an interaction, without having prior information with respect to the subsequent transaction partner [@sokolova_buskens_cooperation_2021; @schneider_weber_cooperation_2013; @brown_etal_relational_2004]. Consistent with the hypothesized effects of control, cooperation increases with the, endogenously chosen, length of an interaction [@schneider_weber_cooperation_2013]. However, note that when embeddedness is established endogenously, actors are no longer randomly assigned to the embeddedness condition, and hence, differences in cooperation under different, endogenously chosen, interaction lengths can no longer be attributed to only these different lengths. Indeed, people who *a priori* indicated a higher willingness to cooperate were more likely to establish a long-term relationship, although this willingness could only partially explain differences in cooperation between one-shot and endogenously chosen long-term relationships [@schneider_weber_cooperation_2013]. 

Additionally, only having the opportunity to engage in long-term interactions already fosters cooperation [@brown_etal_relational_2004]. These findings are in line with the idea that actors realize that having a good reputation may facilitate future lucrative interactions [@kollock_emergence_1994], and that such a reputation can be built by behaving cooperatively. In fact, even at the cost of a portion of subjects' payoffs, these are willing to establish a long-term relationship, and are subsequently more likely to behave cooperatively in this relationship compared to behaviour in one-shot games [@sokolova_buskens_cooperation_2021]. Note that the studies in this review focused on control through "voice", in the sense of @hirschman_voice_1970. Studies on the effect of control through "exit", in which actors can abandon an uncooperative relationship, are omitted from this review for the sake of brevity [interested readers are referred to the work by @schuessler_exit_1989; @hauk_nagel_choice_2001; @hauk_multiple_2003; @zhang_etal_opting_2016]. Although systematic testing of the effect of control on cooperation in endogenous dyadic embedded interactions is, to the best of my knowledge, fairly limited, the available evidence suggests that it likely is at least as strong as in exogenously dyadic embedded interactions. Therefore, both under exogenously and endogenously established dyadic relations, control opportunities foster cooperation between actors.

# Control effects under network embeddedness

The research on control effects through dyadic embeddedness as discussed in the previous sections deliberately ignores an important factor that characterizes many real-life interactions: the involvement of third-parties [@granovetter_economic_1985]. Even if an actor does not engage in a long-term relationship with the same partner, the behaviour of this actor may have consequences for future interactions, albeit with different partners [@kandori_social_1992; @buskens_raub_embedded_2002]. When actors only obtain information about their own interactions, there exists a cooperative Nash equilibrium, where each actor cooperates until the first defection is observed, if the expected number of future interactions is large enough relative to the gains of defection [@kandori_social_1992; @nowak_sigmund_evolution_2005]. Yet, the conditions under which such an equilibrium is supported are fairly restrictive, and the equilibrium itself is extremely unstable. These conditions can be relaxed by introducing information transmission through the network. When there is perfect information, in the sense that information is provided about all interactions, it is theoretically unimportant whether an interaction is embedded dyadically or in a network, as it is the content that matters. When the spread of information is not perfect, in the sense that only part of the information is disseminated, cooperation is expected to increase with the amount of reliable information that is disseminated through the network [for a more detailed discussion, see @raub_weesie_reputation_1990; @kandori_social_1992; and @nowak_sigmund_evolution_2005], and with the importance of future interactions (i.e., the expected number of future interactions), because both factors allow for more severe future sanctions and thus increase control opportunities [for infinitely repeated games, see @raub_weesie_reputation_1990; @kandori_social_1992; @buskens_weesie_cooperation_2000; for finitely repeated games, see @buskens_trust_2003]. Note however that making assumptions on the flow of reliable information about actors' behaviour may be problematic, because whether to share information on someone's behaviour is itself a (second-order) social dilemma, and because actors may face strategic incentives to share misleading information. These issues are deliberately ignored in the current review, because reliable information is provided in all experiments discussed. 

## Control in exogenously embedded interactions in networks

Whereas dyadic embeddedness generally leads to substantially more cooperation due to control effects relative to atomized interactions, the effects of network embeddedness are not so clear-cut. Some studies found support for the hypothesis that cooperation increases with information exchange through the network, in the sense that network embeddedness yielded higher cooperation rates from the first round onwards [@seinen_schram_social_2006; @pfeiffer_etal_value_2012], or found control effects through an end-game effect after controlling for learning [@bolton_electronic_2004]. @corten_etal_reputation_2016, however, have not found any effect of control through network embeddedness on cooperation. These studies, however, differed in the fact that in the former three studies, information was summarized (e.g., a reputation or the total number of cooperative and defective actions were shown to the subjects), whereas in the latter, all previous actions by all actors in the network were shown. Counterintuitively, more information thus does not necessarily result in more cooperation. Additionally, the former three studies differed from the last one in the size of the transaction network. Whereas in the former three studies the network size was at least sixteen, the latter study yielded networks containing six actors. Since the outcomes of own transactions were shown in the condition without network embeddedness in the latter study, the condition with network embeddedness was effectively compared to a condition with a substantial amount of dyadic embeddedness, which may attenuate the effect of network embeddedness.

Additionally, a number of studies focused on the effects of network embeddedness in Trust Games played in triads, with two trustors and one trustee. In these studies, it generally appeared that trustors seldom reap the benefits of network embeddedness, in the sense that network embeddedness does not foster trustfulness, when compared to games with only dyadic embeddedness [@buskens_raub_veer_triads_2010; @miltenburg_buskens_triads_2012; @frey_buskens_investments_2019]. A similar observation was made when the focus was on Investment Games, rather than Trust Games [@barrera_buskens_third_2009]. Hence, the additional control opportunities offered by network embeddedness do not result in more trustfulness of the trustors. Trustees, on the other hand, seem to realize that network embeddedness equips trustors with more sanction opportunities, because the second trustor can sanction the abuse of trust against the first trustor, and vice versa. @buskens_raub_veer_triads_2010 found significant network control effects on the trustworthiness of the trustee, while @frey_buskens_investments_2019 showed, without testing, that first-round trustworthiness increased under exogenous network embeddedness. @miltenburg_buskens_triads_2012 could not find any effects of network control, but in this study, the condition with only dyadic embeddedness already yielded trustworthiness rates of above $80\%$ until the last rounds, leaving little room for improvement under network embeddedness. 

## Control in endogenously embedded interactions in networks

Besides under exogenous embeddedness, network control effects can also be assessed under endogenous embeddedness. Note again that under the assumption of rationality, no differences between exogenously and endogenously embedded interactions are expected. Yet, it has often been remarked that assortment may play an important role in fostering cooperation under endogenously established network embeddedness [e.g., @nowak_evolving_2012; @perc_etal_statistical_2017], because under endogenous network embeddedness, actors can select their partners based on the observation that a potential partner has behaved cooperatively in the past. This allows for new sanction opportunities, in the sense that actors can refuse to engage in a relationship with actors who defected in the past. Yet, relatively few studies assessed cooperation under endogenously established network embeddedness in two-person dilemmas. In fact, to the best of my knowledge, no studies exist that explicitly test control effects in these settings. However, some studies exist that allow to get an initial grasp of control effects under endogenously established network embeddedness. 

@corten_buskens_cooperation_2020, who studied cooperation in dynamic networks of six actors found no support for an effect of network embeddedness, and no indication for a control effect. Note that in this study actors chose to engage in an interaction, and hence cooperation rates were defined as a proportion of the total number of possible interactions. When cooperation was assessed relative to the total number of actual interactions, cooperation was somewhat higher when actors received information about their partners through their network connections, relative to when people only gathered information through their own interactions. However, the effect of network control was not specifically assessed. Additionally, some studies assessed cooperation rates in $N$-person, rather than $2$-person, Prisoner's Dilemmas, which somewhat changes the nature of the game. Without going into the specifics, it appeared that in $N$-person Prisoner's Dilemma games, dynamic partner updating fostered cooperation, but not necessarily due to a control effect [@riedl_ule_2002; @wang_cooperation_2012; @rand_etal_dynamic_2012]. Rather, it appeared that cooperators were allowed to select other cooperators, maintaining high cooperation rates. When no partner updating was possible, these actors more often switched to defection to avoid getting exploited. 

Overall, it appears that the findings on control effects through network embeddedness are mixed. When control effects were found, it mainly affected those actors that were in the position to abuse trust (i.e., both players in a Prisoner's Dilemma game, but only trustees in a Trust Game). The actors that had to place trust generally did not seem to realize that network embeddedness would increase possible sanction opportunities and hence would allow for more trustfulness, or, alternatively, were pessimistic about the extent to which trustees would realize this. Additionally, a substantial part of the effect of endogenously established network embeddedness seems to be attributable to assortment rather than to control. Specifically, cooperators propose ties to other cooperators, while defectors have to change their strategy to be seen as suitable partners. Additionally, when ties with actors that abuse trust can be easily abandoned, cooperative relationships seem to occur somewhat more frequently.

# Conclusion and implications for future research

In the simplest interactions, that is, one-shot interactions in a social vacuum, high levels of cooperation are difficult to sustain when games are played multiple times [@simpson_willer_beyond_2015]. However, this review showed that dyadic embeddedness consistently fosters the establishment of cooperative relationships due to the possibility to control future payoffs of one's interaction partner, both when embeddedness is established exogenously and endogenously. A longer interaction duration, as well as a smaller temptation to defect, are associated with higher cooperation rates, both indicative for a control effect. These effects appeared to increase with the experience of the actors involved. For network embeddedness, similar hypotheses can be formulated, although these were less often tested explicitly, and, if tests were performed, less often confirmed. First of all, the effects of network embeddedness, if present, seem smaller than the effects of dyadic embeddedness, and when both forms of embeddedness operated simultaneously, network embeddedness adds little to the effect of dyadic embeddedness. When actors obtain an easy to interpret reputation, network embeddedness seems to be more effective in promoting cooperation than when actors themselves have to make sense of a long history of played games. Additionally, network embeddedness predominantly affected actors that had the opportunity to abuse trust, and seems to be more effective when the actors involved established their relations endogenously. Yet, in the latter case, the increased effect seems to be due to assortment, in the sense that cooperators end up playing with other cooperators. 

A possible explanation for the fact that positive effects of network embeddedness on cooperation are not always found, could be that past research has often failed to take the importance of experience in playing games into account. Subjects may experience difficulties understanding the relatively complex dynamics of games in networks, especially because actors have to rely on third parties to sanction defectors [@milinski_cooperation_2001]. If actors are unsure whether unilateral defections of their partners will be sanctioned by third parties, they may overestimate the risk of cooperation, and protect themselves by defecting. Since, under network embeddedness, many actors rely on first-order assessment of defective behaviour [i.e., actors base their decision to cooperate on whether their partner cooperated in the previous round; @sigmund_moral_2012], a few initial defections may result in a quick collapse of cooperation [@kollock_emergence_1994]. It is not until participants understand the benefits offered by embeddedness, and hence defect less initially, that cooperation will flourish. Studies that allow for gaining experience throughout the experiment find relatively high cooperation rates [e.g., @wang_cooperation_2012; @frey_buskens_investments_2019], and show that cooperation increases with experience, when cooperation can be supported in equilibrium [e.g., @miltenburg_buskens_triads_2012; @dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011]. The introduction of simplified reputation scores may fasten this process, as it lays less of a cognitive burden on the participants. 

The idea that the complexity of a game complicates the emergence of cooperation is also in line with the finding that trustors generally have more difficulties with reaping the benefits of network embeddedness than trustees. Trustees may relatively quickly understand that behaviour against a given trustor is observed by the second trustor, and hence untrustworthy behaviour can be sanctioned by both trustors. The trustors, however, have to anticipate how the trustee evaluates the presence of two potential sources of sanctioning [see @buskens_raub_veer_triads_2010 for a similar argument]. Additionally, the importance of understanding the dynamics of the game potentially explain why endogenously, rather than exogenously, established embeddedness seems more effective in promoting cooperation. Actors who understand the benefits of embeddedness are more likely to establish embeddedness endogenously, and are subsequently more likely to reap these benefits by behaving cooperatively, while actors who do not see such benefits may be less willing to do so. However, possible effects of experience have been assessed predominantly under dyadic embeddedness. As studies in networks yield more complex dynamics, experience may be even more important. Hence, a thorough assessment of the effects of experience and of the complexity of reputation measures on cooperation in networks could be of great value. 

Methodologically, all empirical studies in the current review employed an experimental design. Multiple papers have been devoted to a discussion of this design [e.g., see @falk_heckman_experiments_2009; @jackson_cox_experimental_2013; @morris_experiments_2014], and the advantages (e.g., the possibility to make causal claims and to disentangle the slightest sources of variation) and disadvantages (e.g., difficulties concerning generalizability to real-world settings, unnatural behaviour of participants due to the research setting) unequivocally apply to the papers discussed in this review. Hence, (longitudinal) observational studies are required to assess whether the experimental findings indeed apply in real-life encounters. Additionally, the studies reviewed are no different from the vast majority of experimental studies, in the sense that a highly selective sample is used. When the complexity of the experiment and the understanding of the participants is indeed related to the level of cooperation observed, the use of, inherently highly educated, university students may provide overly optimistic estimates of the effects of embeddedness. Yet, recent studies involving participants recruited from online labour markets that yield a more representative sample [e.g., @rand_mechanical_turk_2012; @difallah_etal_mechanical_turk_2018], such as Amazon's Mechanical Turk, do not report fundamentally different results [e.g., @rand_etal_dynamic_2012; @pfeiffer_etal_value_2012; @wang_cooperation_2012; @mao_resilient_cooperators_2017]. 

Employing different research designs could possibly overcome some of the limitations inherent to the experimental method, but comes with new challenges. Regarding these different research designs as competitors is unlikely to foster the advancement of science. Rather, it may prove fruitful to integrate the evidence collected under a variety of research designs in a common framework [@jackson_cox_experimental_2013; @munafo_robust_2018; @buskens_raub_handbook_2013]. Namely, a robust line of evidence is necessarily built by combining various ways of testing the same hypotheses, using different sources of data and different methodologies. Recent statistical advances allow for such a unifying approach. Using Bayesian Evidence Synthesis, the support over studies for a given theory, assessed by multiple, different hypotheses concerning the same underlying concept, can be quantified [@kuiper_combining_2013]. This approach allows to expand the classical meta-analytic way of thinking that focuses on statistical reliability, by combining a broader range of relevant studies, leading to a statistical synthesis of conclusions from diverse sources.

There are several directions in which one could proceed using this approach. Consider, for example, the effect of control under exogenously imposed network embeddedness. The studies considered in this review operationalized network embeddedness rather differently, with different network sizes, possibly simultaneous with dyadic embeddedness, in different games, and with varying amounts of experience of the subjects. Hence, obtaining a single estimate of network embeddedness in the sense of a meta-analysis is infeasible. However, if control through network embeddedness fosters cooperation as expected, combined evidence from multiple, diverse sources should confirm this. Under this wide variety of circumstances, one could statistically assess whether an increase in first round cooperation due to network embeddedness adequately summarizes the empirical results, as well as whether network embeddedness leads to a more severe end-game effect. Because both hypotheses essentially represent the effect of control through network embeddedness, one could, using Bayesian Evidence Synthesis, even combine the evidence for both distinct hypotheses. That is, one could quantify the support for both distinct hypotheses over multiple studies into a single measure, to assess whether control through network embeddedness indeed affects cooperation overall. Variations of this approach, such as testing interactions between various hypotheses, are possible, as well as extending the set of studies under consideration with observational studies, field experiments and vignette studies, to get a broad, statistically substantiated quantification of the overall hypothesis that network embeddedness fosters cooperation.



<!--
**REMOVE AND PLACE IN DISCUSSION**
Lastly, although the evidence consistently shows that first round cooperation increases with the (expected) number of rounds left, there remains substantial heterogeneity in cooperation rates, even in games of approximately the same length. Whereas @cooper_et_al_cooperation_1996 find cooperation rates in finitely repeated games of around 65%, @embrey_etal_cooperation_2018 find above 80% cooperation and @mao_resilient_cooperators_2017 observes near perfect cooperation, all in the first round, even though all games have a fixed end at round 10 and differences in the payoff matrix are only minor. A possible explanation of this finding may be the differences in economic incentives between the study. In the study by @cooper_et_al_cooperation_1996, participants' points were translated into probabilities of winning a monetary price, rather than translated directly into money. Due to this chance component, subjects may have been less motivated to maximize their returns of the game. In @embrey_etal_cooperation_2018 and @mao_resilient_cooperators_2017, players' monetary payoffs were directly, linearly, derived from their number of points.

Past research has shown that cooperation is often vulnerable, and an initial pattern of actors that try to exploit each other may easily result in a collapse of cooperation [@kollock_emergence_1994]. In studies on network embeddedness, this result could be exaggerated, as an initial defection against any given player may result in a new defection against the initial defecting actor. Subsequently, interaction partners of both the first and the second defector may abstain from cooperation, resulting of a collapse of cooperating behaviour under network embeddedness. Indeed, under network embeddedness, many actors seem to rely on first-order assessment of defective behaviour [@sigmund_moral_2012]. That is, actors base their decision to cooperate on the observed cooperativeness of their transaction partners in the past, without taking past behaviour of their partners into account. While this assessment rule might work under dyadic embeddedness, where the reason of one's partner's action can be inferred, it does not do well under network embeddedness. However, tracking whether one's partner's past behaviour against third parties were the result earlier defections against this partner is generally difficult [@milinski_cooperation_2001; @nowak_sigmund_evolution_2005]. Even though this explanation does not account for the absence of control effects under network embeddedness if network embeddedness is measured as first round cooperation, actors who experienced such a collapse of cooperation may infer that they deal with a relatively opportunistic population, and hence defect in early rounds of subsequent games within the the given experiment. Subsequently, average first round cooperation rates may be severely affected. 

Yet, the previous argument does not seem to be the main reason why network embeddedness does not always foster cooperation, and why a control effect may be absent in such situations. A more plausible explanation of the finding that cooperation does not always prevail under network embeddedness, could be that it takes time to understand complex dynamics of games in networks. Already under simpler conditions, like dyadically embedded repeated interactions, ample studies show that initial games may fail to reach cooperative relationships, even though cooperation can be supported in equilibrium [e.g., @miltenburg_buskens_triads_2012; @dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011]. With sufficient experience, participants seem to understand the crucial aspects that are required to fully reap the benefits that are offered by embeddedness. However, only three studies on network embeddedness [i.e., @miltenburg_buskens_triads_2012; @wang_cooperation_2012; @frey_buskens_investments_2019], which may be not accidentally the studies that reached high levels of cooperation, allowed for gaining experience by letting the subjects play a substantial number of games. However, it must be noted that the study @frey_buskens_investments_2019 only showed marginally higher first round trustfulness rates under exogenously embedded interactions than under dyadic embeddedness. 

The difficulties participants may have with understanding the possible favourable effect of network embeddedness on cooperation through network embeddedness is also in line with the finding that trustors generally have more difficulties with exploiting the benefits of network embeddedness than trustees. 

Difficulties subjects may have with understanding complex dynamics of games in networks could also explain why endogenously established network embeddedness can foster cooperation to a greater extend than exogenously established embeddedness. 

One of the fundamental advantages of the research discussed in this review is the use of the experimental method, in which participants are randomly assigned to treatment conditions. All differences between the treatment groups are attributable to the differences between the treatment conditions, which allows researchers to estimate causal effects that are hard to assess using observational data. Yet, there is no such thing as a free lunch. The vast majority of the experiments discussed in this review used a highly selective sample of participants, at least in terms of education and origin. Namely, most experiments relied on university students from Western universities. Although @snijders_keren_trust_2001 showed that in relatively simple social dilemmas (i.e., Prisoner's Dilemma Games and Trust Games), the findings under a sample of undergraduate students did not differ from a representative sample of the Dutch population, the experiments on embeddedness effects generally employ a more complex design. If one's understanding of the effects of embeddedness indeed affects trust, it might be that findings obtained in this study are in fact overly optimistic, as participants with lower educational achievement might generally have more difficulties to grasp such complex dynamics. A few studies relied on participants from online labour markets such as Amazon's Mechanical Turk, which provides some advantages in the form costs due to easy recruitment and a more representative sample, although at the cost of lacking a controlled environment [@rand_mechanical_turk_2012; @difallah_etal_mechanical_turk_2018].

[The next section is really something that I sometimes struggle with, and I still have to examine if there is literature on this (probably there is) and what the literature says, so I don't know whether I will incorporate this in the final review.]
An additional drawback of the experiments used in this review is that they often were relatively artificial in nature. Although this approach allows to separate the slightest sources of variation that can seldom be disentangled using observational data, it is often not clear how results obtained in the lab translate to real-life settings. In fact, these experiments have difficulties with explaining why humans behave as they behave in real-life encounters, as it is hardly taken into account how taking people out of their social context affects their behaviour. More specifically, it is the question to what extent letting the participants play games brings about competitive behaviour that the participants do not show in real-life settings. This feature may be overcome by using modern data sources, such as social media data and data from online trading platforms, which is increasingly being done [e.g., studies by Diekmann for example]. These rich data sources may provide information on how people behave in more natural settings, while allowing for disentangling a wide variety of different mechanisms that possibly affect trust. The use of observational data to test the mechanisms identified in experimental research may also be of importance. Especially the use of various, differing designs and methods may prove to be a fruitful method to combine the best aspects of different data sources [@munafo_robust_2018; @kuiper_combining_2013; @buskens_raub_handbook_2013].

Lastly, most research on embeddedness assesses how different relations between actors, such as dyadic embeddedness and network embeddedness that may or may not be established endogenously, affects cooperation. However, in a substantial proportion of this research, the mechanisms that promote cooperation remain relatively implicit. Hence, it becomes clear that certain manipulations affect cooperative behaviour, but not why exactly these manipulations work, or, alternatively, what aspects of these manipulations make these changes come about. For example, some studies showed that endogenously established embeddedness fosters cooperation. Yet, there may be multiple reasons why endogenously established embeddedness fosters cooperation. For example, it may be due to assortment, it may be due to the actors establishing embeddedness understanding the benefits of establishing, and it may be that embeddedness on itself induces more cooperation. However, only a minority of the research in this area actually tries to disentangle these different sources through which embeddedness may affect trust [e.g., see @buskens_raub_embedded_2002; @buskens_raub_handbook_2013]. Future research may play a vital role by deepening the understanding of the mechanisms that affect trust to a greater detail. 


**Static network structure can stabilizehuman cooperationDavid G. Randa,b,c,d,1, Martin A. Nowake,f,g, James H. Fowlerh,i, and Nicholas A. Christakis remark that experimentation undermines the ability of networks to promote cooperation (and that participants may rely on experimentation if they do not fully grasp the dynamics of the game).


<!-- The available evidence rather consistently shows that more control opportunities induce more cooperation. Although the introduction of embeddedness narrows the gap to real-life interactions, an overwhelming amount of the experiments conducted remains rather artificial in nature. This approach has clear advantages, as it allows to separate the slightest sources of variation that would be entangled in survey research and to assess the causal effect of changing certain features of an interaction on cooperation. However, these artificial experiments do little in explaining why humans behave as they behave in real-life encounters, as it is hardly assessed how taking people out of their social context affects their behaviour. -->

<!-- Axelrod Launching ‘The Evolution of Cooperation’ - "There were several limitations in using people - even skilled people - to study how to best play the Prisoner's Dilemma.  -->

<!-- Why does dyadic embeddedness foster cooperation more than network embeddedness. @sigmund_moral_2012 argues that under network embeddedness, many players seem to rely on first-order assessment. That is, actors base their decision to cooperate on the observed cooperativeness of their transaction partners in the past. While this assessment rule might work under dyadic embeddedness, where the reason of one's partner's action can be inferred, it does not do well under network embeddedness. However, tracking whether one's partner's past behaviour against third parties were the result earlier defections against this partner is generally difficult [@milinski_cooperation_2001 is referred that higher order assessment is cognitively taxing]. -->

<!-- @kollock_emergence_1994 on experiments: "[T]he typical social exchange experiment guarantees the terms of exchange. In one sense this is an understandable feature of an experimental paradigm if one wishes to study, for example, the dynamics of power in a controlled way, but in another sense it sidesteps much that is crucial in actual interaction (concerns of uncertainty, risk, and being taken advantage of) and thus much that may be central in explaining why social structure in the form of networks of commitment exists. -->

<!-- Most studies in this field of research are narrowed down to assess how small changes in conditions affect cooperation, providing insight in multiple potentially important mechanisms that affect cooperation. This has led to a wide variety of factors that in one way or another affect cooperation when studied in isolation. A numerous amount of studies focused on cooperation in dyadically embedded relations, formed either exogenously or endogenously, to investigate what aspects of an interaction may foster and complicate cooperation. Additionally, there are numerous studies that assess how network embeddedness fosters cooperation, most of them focusing on a relatively small aspect of the network. However, these studies suffer from two important limitations. First, most experiments rely on an artificial and often greatly simplified social context, regardless of whether the focus of the studies is dyadic or network embeddedness. Hence, the extent to which findings from these experiments can be translated to everyday life is often questionable. Second, focusing on relatively small changes between conditions may complicate an assessment of the bigger picture. Predominantly, factors that seem important for cooperation when studied in isolation, may appear trivial when multiple factors are assessed simultaneously.  -->

<!-- The majority of experimental studies on dyadic embeddedness do not allow for leaving a defective relationship, with @brown_etal_relational_2004 as one of the rare exceptions. See also Hauk (2003; https://link.springer.com/content/pdf/10.1023/A:1027385819400.pdf) Yet, this feature is often covered in studies on network embeddedness. See e.g. Buskens 2003 for a theoretical outline of the effect of leaving opportunities. -->



<!-- Rand (2012) from Nowok - Evolving cooperation (2012) suggests that online labor markets such as Amazon's Mechanical Turk provide a useful platform for conducting behavioural experiments. -->

<!--However, the question is whether it is actually control that fosters cooperation in repeated interactions. Namely, the prospect of future benefits that by far outweigh the gains of short-term opportunistic behaviour can possibly be realized without any control. Consider a game in which after the end of every round, the subjects involved unilaterally decide to break of the interaction. That is, the subjects play a one-shot game, and after the game, they can decide whether they want to play the same game with each other. There is no control in a strict sense, because future interactions depend on choices made after the game. However,-->

<!--
# Conclusion

This review shed light on the effects of control through exogenously and endogenously established dyadic and network embeddedness on cooperative behaviour. It is shown that control through dyadic embeddedness positively affects cooperation, regardless of whether it was established exogenously or endogenously. The effects of control through network embeddedness were far less clear cut, although it seems that in the simplest settings and with sufficient experience, actors see the benefits of network embeddedness. Yet, there is still a lot to gain in this area, predominantly with regard to what mechanisms exactly foster cooperation under network embeddedness. In this paper, it was tried to provide some directions toward which future research might head. 

[This has to be extended, but I think that this is the main message.]

<!--
In these studies, causality is generally not an issue. The majority of the reviewed literature makes use of the experimental method, that allows the researcher to attribute changes in the outcome to the varying conditions. In this way, experimental research overcomes some of the difficulties of non-experimental field data that is typically difficult to replicate and does seldom allow for causal inference [fehr_gintis_2007; ADD BIBTEX]. The primary problem of this line of research lies in the external validity of the results. The fact that theories prove their usefulness in a laboratory does not necessarily say much about these mechanisms in the real world. 

Additionally, most experimental work has a hard time identifying the mechanism through which cooperation occurs. There is (???) evidence for the effect of control, but these effects are often hard to tell apart from direct sanctioning or learning models. 
-->

<!--
## Experiment idea

To test the notion of network embeddedness in comparison to dyadic embeddedness, one can employ the following design. Players are randomly allocated to a network of X players, with X somewhere between 4 to 6. In this network, they play games with a randomly drawn other in every round, with certain continuation probability $p$ that there is a subsequent round after the round that is currently played, with $p$ for example 3/4. 
-->

# Literature

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\noindent

<div id="refs"></div>

\appendix

\setlength{\parindent}{0.2in}
\setlength{\leftskip}{0in}

# Appendix 1 - Thesis proposal

In the past review, it became apparent that dyadic embeddedness consistently fosters cooperation. However, despite similar theoretical predictions (see Section \ref{control-effects-through-network-embeddedness}), network embeddedness proves much less efficient in fostering embeddedness. In fact, it is questionable to what extent network embeddedness fosters cooperation at all. The first goal of the thesis will be to statistically summarize the available evidence on control effects through network embeddedness, using past experimental studies of which available data is present [@buskens_raub_veer_triads_2010; @miltenburg_buskens_triads_2012; @corten_etal_reputation_2016; @frey_buskens_investments_2019; @barrera_buskens_third_2009]. Data from other studies [e.g., @bolton_electronic_2004] can be a great addition, but the current project does not depend on the availability of additional data. In these studies, specific predictions that represent control effects through network embeddedness can be tested, such as an increase in first round cooperation rates under network embeddedness, a positive effect on cooperation of the number of rounds that are to be played (after controlling for learning) and an end-game effect that starts later under network embeddedness. In the thesis, I will use Bayesian Evidence Synthesis [@kuiper_combining_2013] to quantify the overall support for these hypotheses separately, and I will combine the evidence for all these hypotheses into a single measure, as the distinct hypotheses all represent effectively the same mechanism.

Additionally, the characteristics of a relation that are argued to foster cooperation, such as the length of a game and the temptation to defect, are thoroughly tested under dyadic embeddedness [@dal_bó_cooperation_2005; @dal_bó_fréchette_evolution_2011; @embrey_etal_cooperation_2018]. Network embeddedness yields similar predictions, but such predictions, especially on the length of the supergame, are hardly tested. If time and resources allow to do so, it could be of great value to design a new experiment, in which it can be tested whether the conditions that are well-known to foster cooperation under dyadic embeddedness have a similar effect under network embeddedness.^[This new experiment idea is not discussed at all with my supervisors, but it came up while writing the conclusion, after which I had no time to discuss any of it. The primary goal of the thesis will be a synthesis of network control effects, as outlined in the previous paragraph, and this section is a possible extension of the project.] Additionally, the current literature review provided a preliminary indication that how one's past action are translated into a reputation (a complete history of past actions, a reputation score depending on some rule that is updated every round, a summary of past actions) affects cooperation. If the complexity of the dynamics of the game indeed affect cooperation, it can be expected that more complex reputation measures foster cooperation less than simpler alternatives, even though simpler measures may come with additional complications [see e.g., @nowak_sigmund_evolution_2005]. 

This set-up might lead to a new experiment with a three-way full factorial design, in which the length of the game, the temptation to defect and the reputation measure are varied. One could think of an experiment in which three continuation probabilities (e.g., $\delta \in \{0, 1/2, 3/4\}$) are crossed with two different gains (losses) of unilateral defection (cooperation) and two measures of reputation. For the duration of the supergame, subjects can be matched randomly every round, but take their reputation with them, until the supergame ends. Subjects can play multiple supergames until, say, $1.5$ hours passed. This set up allows subjects to gain familiarity with the dynamics of the game. The results from this experiment can be incorporated in the synthesis of all available evidence.



